// Register Member
export const REGISTER_MEMBER_REQUEST = "REGISTER_MEMBER_REQUEST";
export const REGISTER_MEMBER_SUCCESS = "REGISTER_MEMBER_SUCCESS";
export const REGISTER_MEMBER_FAIL = "REGISTER_MEMBER_FAIL";

// Fetch Members
export const FETCH_MEMBER_REQUEST = "FETCH_MEMBER_REQUEST";
export const FETCH_MEMBER_SUCCESS = "FETCH_MEMBER_SUCCESS";
export const FETCH_MEMBER_FAIL = "FETCH_MEMBER_FAIL";

// Single Member
export const SINGLE_MEMBER_REQUEST = "SINGLE_MEMBER_REQUEST";
export const SINGLE_MEMBER_SUCCESS = "SINGLE_MEMBER_SUCCESS";
export const SINGLE_MEMBER_FAIL = "SINGLE_MEMBER_FAIL";

// Update Member
export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAIL = "UPDATE_MEMBER_FAIL";
export const UPDATE_MEMBER_RESET = "UPDATE_MEMBER_RESET"; // Add this line

// Delete Member
export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAIL = "DELETE_MEMBER_FAIL";
export const DELETE_MEMBER_RESET = "DELETE_MEMBER_RESET"; // Add this line

// Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
