

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const REGISTER_MEMBER_REQUEST = 'REGISTER_MEMBER_REQUEST'
export const REGISTER_MEMBER_SUCCESS = 'REGISTER_MEMBER_SUCCESS'
export const REGISTER_MEMBER_FAIL = 'REGISTER_MEMBER_FAIL'

export const FETCH_MEMBER_REQUEST = 'FETCH_MEMBER_REQUEST'
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS'
export const FETCH_MEMBER_FAIL = 'FETCH_MEMBER_FAIL'

export const SINGLE_MEMBER_REQUEST = 'SINGLE_MEMBER_REQUEST'
export const SINGLE_MEMBER_SUCCESS = 'SIGNLE_MEMBER_SUCCESS'
export const SINGLE_MEMBER_FAIL = 'SINGLE_MEMBER_FAIL'

export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS'
export const UPDATE_MEMBER_FAIL = 'UPDATE_MEMBER_FAIL'

export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAIL = 'DELETE_MEMBER_FAIL'